<%@ Page Title="Clientes" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Clientes.aspx.cs" Inherits="ProyectoProgramacion2.Clientes" EnableEventValidation="true" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="container mt-5">
        <h2 class="text-center text-light mb-4">Formulario de Clientes</h2>

        <div class="bg-dark p-4 rounded shadow-lg">
            <div class="form-group row">
                <label for="txtNombre" class="col-sm-3 col-form-label text-light">Nombre:</label>
                <div class="col-sm-9">
                    <asp:TextBox ID="txtNombre" runat="server" CssClass="form-control bg-secondary text-light" placeholder="Ingrese su nombre"></asp:TextBox>
                    <asp:RequiredFieldValidator runat="server" ID="rfvNombre" ValidationGroup="formRequerido" ControlToValidate="txtNombre" CssClass="text-danger small" Text="El nombre es requerido."></asp:RequiredFieldValidator>
                </div>
            </div>

            <div class="form-group row">
                <label for="txtApellido" class="col-sm-3 col-form-label text-light">Apellido:</label>
                <div class="col-sm-9">
                    <asp:TextBox ID="txtApellido" runat="server" CssClass="form-control bg-secondary text-light" placeholder="Ingrese su apellido"></asp:TextBox>
                    <asp:RequiredFieldValidator runat="server" ID="rfvApellido" ValidationGroup="formRequerido" ControlToValidate="txtApellido" CssClass="text-danger small" Text="El apellido es requerido."></asp:RequiredFieldValidator>
                </div>
            </div>

            <div class="form-group row">
                <label for="txtCI" class="col-sm-3 col-form-label text-light">Cédula de Identidad:</label>
                <div class="col-sm-9">
                    <asp:TextBox ID="txtCI" TextMode="Number" runat="server" CssClass="form-control bg-secondary text-light" placeholder="Ingrese su cédula"></asp:TextBox>
                    <asp:RequiredFieldValidator runat="server" ID="rfvCI" ValidationGroup="formRequerido" ControlToValidate="txtCI" CssClass="text-danger small" Text="El número de documento es requerido."></asp:RequiredFieldValidator>
                </div>
            </div>

            <br />
            <div class="form-group row">
                <label for="txtDireccion" class="col-sm-3 col-form-label text-light">Dirección:</label>
                <div class="col-sm-9">
                    <asp:TextBox ID="txtDireccion" runat="server" ValidationGroup="formRequerido" CssClass="form-control bg-secondary text-light" placeholder="Ingrese su dirección"></asp:TextBox>
                </div>
            </div>
            <br />
            <div class="form-group row">
                <label for="txtTelefono" class="col-sm-3 col-form-label text-light">Teléfono:</label>
                <div class="col-sm-9">
                    <asp:TextBox ID="txtTelefono" runat="server" CssClass="form-control bg-secondary text-light" placeholder="Ingrese su teléfono"></asp:TextBox>
                </div>
            </div>
            <br />
            <div class="form-group row">
                <label for="txtEmail" class="col-sm-3 col-form-label text-light">Correo electrónico:</label>
                <div class="col-sm-9">
                    <asp:TextBox ID="txtEmail" runat="server" CssClass="form-control bg-secondary text-light" placeholder="Ingrese su correo electrónico"></asp:TextBox>
                    <asp:RegularExpressionValidator ID="revEmail" runat="server" ValidationGroup="formRequerido" ControlToValidate="txtEmail" ErrorMessage="Ingresa un correo válido" ValidationExpression="^[^@\s]+@[^@\s]+\.[^@\s]+$" CssClass="text-danger small"></asp:RegularExpressionValidator>
                </div>
            </div>
            <br />
            <div class="form-group text-center mt-4">
                <asp:Button ID="cmdVer" runat="server" Text="Crear Cliente" CausesValidation="true" ValidationGroup="formRequerido" CssClass="btn btn-primary px-4" OnClick="cmdVer_Click" />
            </div>
        </div>
        <br />
        <h3 class="text-center text-light mt-5">Lista de Clientes</h3>
        <div class="table-responsive">
            <asp:GridView ID="gvClientes" runat="server" CssClass="table table-dark table-hover text-center" AutoGenerateColumns="False" DataKeyNames="CI"
                AutoGenerateEditButton="True" AutoGenerateDeleteButton="True"
                OnRowEditing="EditarClientes" OnRowUpdating="ActualizarClientes"
                OnRowDeleting="BorrarClientes" OnRowCancelingEdit="CanceloEditarClientes">
                <Columns>
                    <asp:BoundField DataField="Nombre" HeaderText="Nombre" />
                    <asp:BoundField DataField="Apellido" HeaderText="Apellido" />
                    <asp:BoundField DataField="CI" HeaderText="Cédula de Identidad" />
                    <asp:BoundField DataField="Direccion" HeaderText="Dirección" />
                    <asp:BoundField DataField="Telefono" HeaderText="Teléfono" />
                    <asp:BoundField DataField="Email" HeaderText="Correo Electrónico" />
                </Columns>
            </asp:GridView>
        </div>

        <asp:Label ID="lblError" runat="server" Visible="false" CssClass="text-danger"></asp:Label>
    </div>
</asp:Content>
